# Filesystem Proxy Actor
name = "fs-proxy"
version = "0.1.0"
description = "A proxy actor that provides controlled access to the filesystem"

[interface]
implements = "ntwk:theater/actor"
requires = []

[[handlers]]
type = "filesystem"
config = { path = "{{fs_path}}" }

[[handlers]]
type = "message-server"
config = { port = "{{message_port}}" }
interface = "ntwk:theater/message-server-client"